#!/usr/bin/env python3
"""Generate app_en.arb and app_he.arb for BuddBull l10n."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "lib" / "l10n"

EN = {
    "@@locale": "en",
    "appName": "BuddBull",
    "appTagline": "Find your squad. Play your game.",
    "welcomeBack": "Welcome back!",
    "loginSubtitle": "Sign in to your BuddBull account",
    "emailLabel": "Email address",
    "emailHint": "you@example.com",
    "passwordLabel": "Password",
    "passwordHint": "Your password",
    "forgotPassword": "Forgot password?",
    "loginButton": "Sign In",
    "noAccount": "Don't have an account?",
    "signUpLink": "Sign up",
    "createAccount": "Create Account",
    "registerSubtitle": "Join BuddBull — it's free!",
    "firstNameLabel": "First name",
    "firstNameHint": "Alex",
    "lastNameLabel": "Last name",
    "lastNameHint": "Rivera",
    "usernameLabel": "Username",
    "usernameHint": "@username",
    "confirmPasswordLabel": "Confirm password",
    "confirmPasswordHint": "Repeat your password",
    "roleLabel": "I want to…",
    "rolePlayer": "Join games as a Player",
    "roleOrganizer": "Organize & Captain games",
    "termsAgreement": "I agree to the ",
    "termsOfService": "Terms of Service",
    "andText": " and ",
    "privacyPolicy": "Privacy Policy",
    "registerButton": "Create Account",
    "haveAccount": "Already have an account?",
    "signInLink": "Sign in",
    "resetPassword": "Reset Password",
    "forgotSubtitle": "Enter your email and we'll send you a reset link.",
    "sendResetLink": "Send Reset Link",
    "backToLogin": "Back to Sign In",
    "resetEmailSent": "Reset email sent! Check your inbox.",
    "myProfile": "My Profile",
    "editProfile": "Edit Profile",
    "bioLabel": "Bio",
    "bioHint": "Tell us a bit about yourself…",
    "cityLabel": "City",
    "neighborhoodLabel": "Neighbourhood",
    "radiusLabel": "Search radius (km)",
    "sportsInterests": "Sports & Skill Levels",
    "addSport": "+ Add sport",
    "saveChanges": "Save Changes",
    "changePhoto": "Change Photo",
    "friends": "Friends",
    "gamesPlayed": "Games",
    "rating": "Rating",
    "streakDays": "Streak",
    "beginner": "Beginner",
    "amateur": "Amateur",
    "intermediate": "Intermediate",
    "advanced": "Advanced",
    "professional": "Professional",
    "loading": "Loading…",
    "retry": "Retry",
    "cancel": "Cancel",
    "save": "Save",
    "delete": "Delete",
    "confirm": "Confirm",
    "yes": "Yes",
    "no": "No",
    "close": "Close",
    "fieldRequired": "This field is required.",
    "invalidEmail": "Enter a valid email address.",
    "passwordTooShort": "Password must be at least 8 characters.",
    "passwordsNoMatch": "Passwords do not match.",
    "usernameTooShort": "Username must be at least 3 characters.",
    "acceptTerms": "You must accept the Terms of Service.",
    "onboardingWelcomeMessage": "Welcome to BuddBull! Let's get to know you better.",
    "onboardingSportsSection": "What are your favourite sports? Tap to select — you can change this anytime.",
    "onboardingSkillPerSport": "Your level in each sport",
    "onboardingNext": "Next",
    "onboardingBack": "Back",
    "onboardingSkip": "Skip",
    "onboardingLocationTitle": "Where do you live?",
    "onboardingLocationSubtitle": "We use your area to match you with nearby games. Pick your city to continue.",
    "onboardingLocationCityHint": "Start typing your city…",
    "onboardingLocationNeighborhoodHint": "Optional — neighbourhood or area",
    "locationPermissionDenied": "Location access is needed to find games near you. Enable it in settings or use city search.",
    "onboardingProfileTitle": "Make it yours",
    "onboardingProfileSubtitle": "Upload a photo or pick a Buddy avatar. You can always update later.",
    "onboardingUploadPhoto": "Upload from device",
    "onboardingOrPickAvatar": "Or choose a starter avatar",
    "onboardingFinish": "Get started",
    "genericError": "Something went wrong. Please try again.",
    "networkError": "No internet connection. Check your network.",
    "serverError": "Server error. Please try again later.",
    "sessionExpired": "Your session has expired. Please sign in again.",
    "unauthorised": "You are not authorised to do that.",
    "resourceNotFound": "Resource not found.",
    "conflictError": "A conflict occurred.",
    "badRequestError": "Invalid request.",
    "validationError": "Validation failed.",
    "rateLimitedError": "Too many requests. Please slow down.",
    "authFailed": "Authentication failed. Please try again.",
    "navHome": "Home",
    "navGames": "Games",
    "navChat": "Messages",
    "navPerformance": "Performance",
    "navProfile": "Profile",
    "oops": "Oops!",
    "language": "Language",
    "languageEnglish": "English",
    "languageHebrew": "עברית",
    "searchGamesPlayersHint": "Search games, players…",
    "tooltipMyCalendar": "My calendar",
    "fabAddGame": "Add Game",
    "fabLogTraining": "Log Training",
    "pageNotFound": "Page not found",
    "settingsTitle": "Settings",
    "pushNotifications": "Push Notifications",
    "pushNotificationsSubtitle": "Receive notifications about activities",
    "activityReminders": "Activity Reminders",
    "activityRemindersSubtitle": "Remind me before scheduled activities",
    "darkMode": "Dark Mode",
    "darkModeSubtitle": "Use dark theme",
    "appVersion": "App Version",
    "notificationsEnabled": "Notifications enabled",
    "notificationsDisabled": "Notifications disabled",
    "remindersEnabled": "Activity reminders enabled",
    "remindersDisabled": "Activity reminders disabled",
    "darkModeEnabled": "Dark mode enabled",
    "darkModeDisabled": "Dark mode disabled",
    "tooltipAdminDashboard": "Admin Dashboard",
    "tooltipEditProfile": "Edit profile",
    "tooltipSignOut": "Sign out",
    "mutualConnections": "{count, plural, =0{No mutual connections} =1{1 mutual connection} other{{count} mutual connections}}",
    "sectionAbout": "About",
    "sectionLocation": "Location",
    "locationRadiusKm": "{radius} km radius",
    "sectionRecentActivity": "Recent Activity",
    "dialogSignOutTitle": "Sign out?",
    "dialogSignOutBody": "You will need to sign in again.",
    "signOut": "Sign out",
    "winRatePercent": "Win Rate %",
    "communityAverageRating": "Community average {rating} from {count} {ratingWord}",
    "ratingSingular": "rating",
    "ratingsPlural": "ratings",
    "sectionSports": "Sports",
    "sectionRatingsSummary": "Ratings Summary",
    "metricOverall": "Overall",
    "metricReliability": "Reliability",
    "metricBehavior": "Behavior",
    "sectionUpcomingGames": "Upcoming Games",
    "snackFriendRequestSent": "Friend request sent",
    "snackNowFriends": "You are now friends",
    "snackFriendRequestDeclined": "Friend request declined",
    "snackSignInToMessage": "Please sign in to send a message.",
    "snackCannotMessageSelf": "You cannot message yourself.",
    "buttonMessage": "Message",
    "buttonRequestSent": "Request sent",
    "buttonAccept": "Accept",
    "buttonDecline": "Decline",
    "buttonAddFriend": "Add Friend",
    "noRatingsYet": "No ratings yet",
    "activityDurationMinutes": "{minutes} min",
    "greetingGoodMorning": "Good morning",
    "greetingGoodAfternoon": "Good afternoon",
    "greetingGoodEvening": "Good evening",
    "greetingWithName": "{greeting}, {firstName}!",
    "greetingNoName": "{greeting}!",
    "homeCollapsedTitleFallback": "BuddBull",
    "tooltipNotifications": "Notifications",
    "statGames": "Games",
    "statRating": "Rating",
    "statStreak": "Streak",
    "streakDaysSuffix": "{days}d",
    "sectionMyUpcomingGames": "My Upcoming Games",
    "actionSeeAll": "See all",
    "sectionExploreNearYou": "Explore Near You",
    "actionBrowseAll": "Browse all",
    "sectionQuickActions": "Quick Actions",
    "quickActionFindGame": "Find a Game",
    "quickActionLogSession": "Log Session",
    "quickActionCreateGame": "Create Game",
    "sectionRecentActivity": "Recent Activity",
    "emptyNoRecentSessions": "No recent sessions",
    "actionLogSession": "Log a session",
    "emptyNoUpcomingGames": "No upcoming games",
    "actionBrowseGames": "Browse games",
    "emptyCouldntLoadNearbyGames": "Couldn't load nearby games",
    "emptyNothingNearby": "Nothing nearby right now",
    "tooltipCreateGame": "Create game",
    "searchGamesHint": "Search games, sports, locations…",
    "tooltipFilter": "Filter",
    "sportFilterAll": "All",
    "sportFootball": "Football",
    "sportBasketball": "Basketball",
    "sportTennis": "Tennis",
    "sportRunning": "Running",
    "sportSwimming": "Swimming",
    "sportCycling": "Cycling",
    "sportVolleyball": "Volleyball",
    "sportCricket": "Cricket",
    "filtersActive": "{count, plural, =1{1 filter active} other{{count} filters active}}",
    "clearFilters": "Clear",
    "emptyNoGamesFound": "No games found",
    "emptyTryAdjustingFilters": "Try adjusting your filters or create a new game.",
    "buttonCreateGame": "Create a game",
    "filterGames": "Filter Games",
    "clearAll": "Clear all",
    "sport": "Sport",
    "nearMe": "Near me",
    "requiredSkillLevel": "Required skill level",
    "createGameTitle": "Create Game",
    "gameTitleLabel": "Game title *",
    "descriptionLabel": "Description",
    "dateAndTime": "Date & Time *",
    "durationHours": "Duration: {hours}h {minutes}min",
    "durationMinutesOnly": "{minutes}min",
    "locationRequired": "Location *",
    "addressLabel": "Address *",
    "venueNameLabel": "Venue name",
    "maxPlayersLabel": "Max players: {count}",
    "visibility": "Visibility",
    "gameCreatedSuccess": "Game created! 🎉",
    "editGameTitle": "Edit Game",
    "gameUpdatedSuccess": "Game updated!",
    "myCalendar": "My Calendar",
    "today": "Today",
    "noGamesOnDay": "No games on this day",
    "joinRequestDeclinedSnack": "Your request to join was declined. You can try again below.",
    "infoLabelDate": "Date",
    "infoLabelTime": "Time",
    "infoLabelDuration": "Duration",
    "sectionAboutThisGame": "About this game",
    "sectionOrganiser": "Organiser",
    "sectionPlayers": "Players",
    "sectionMatchResult": "Match Result",
    "sectionTags": "Tags",
    "mapPreviewUnavailable": "Map preview unavailable",
    "playerListApproved": "Approved",
    "playerListPendingRequests": "Pending requests",
    "playerYouSuffix": "(You)",
    "buttonRate": "Rate",
    "tooltipApprove": "Approve",
    "tooltipKick": "Kick",
    "ratePromptBanner": "Rate participants below to share how the game went.",
    "matchResultScore": "Score: {score}",
    "matchResultWinner": "Winner: {winner}",
    "gameStatusOpen": "Open",
    "gameStatusFull": "Full",
    "gameStatusLive": "Live",
    "gameStatusCompleted": "Completed",
    "gameStatusCancelled": "Cancelled",
    "reportGame": "Report Game",
    "buttonChat": "Chat",
    "buttonRateParticipants": "Rate Participants",
    "buttonLeaveGame": "Leave Game",
    "buttonGameCompleted": "Game Completed",
    "buttonManageOrganiser": "Manage (Organiser)",
    "buttonGameIsFull": "Game is Full",
    "buttonRequestToJoin": "Request to Join",
    "buttonJoinGame": "Join Game",
    "inviteBannerTitle": "You're invited to this game",
    "buttonAcceptInvitation": "Accept Invitation",
    "pendingApprovalMessage": "Your request is pending approval",
    "buttonWithdraw": "Withdraw",
    "inviteFriendsSheetTitle": "Invite Friends",
    "inviteFriendsEmptyState": "Add friends from their profile to invite them to games.",
    "buttonInvited": "Invited",
    "snackInvitedFriend": "Invited {friendName}",
    "snackRevokedInvite": "Revoked invite for {friendName}",
    "manageInviteFriends": "Invite Friends",
    "manageInviteFriendsSubtitle": "Send an invite to your approved friends",
    "manageEditGame": "Edit Game",
    "manageViewSummaryRatePlayers": "View Summary / Rate Players",
    "manageViewSummarySubtitle": "Game is finished — open the rating flow for participants.",
    "manageCompleteGame": "Complete Game",
    "manageCompleteGameSubtitle": "Mark the game as finished and open ratings for participants.",
    "manageGameAlreadyCancelled": "Game already cancelled",
    "manageCancelGame": "Cancel Game",
    "snackGameCancelled": "Game cancelled.",
    "dialogCancelGameTitle": "Cancel game?",
    "dialogCancelGameBody": "This will mark the game as cancelled for all players.",
    "dialogYesCancel": "Yes, cancel",
    "dialogCompleteGameTitle": "Complete game?",
    "dialogCompleteGameBody": "This marks the game as finished, updates player stats, and unlocks rating for all approved players. This action cannot be undone.",
    "dialogNotYet": "Not yet",
    "dialogMarkCompleted": "Mark completed",
    "snackCouldNotLoadPendingRatings": "Could not load pending ratings. Pull to refresh and try again.",
    "fallbackPlayerName": "Player",
    "snackEveryoneRated": "Everyone in this game has been rated.",
    "rateParticipantPickerTitle": "Rate a participant",
    "dontRateThisGame": "Don't rate this game",
    "snackWontPromptToRate": "You will not be prompted to rate this game.",
    "dialogCancelReasonTitle": "Reason for cancellation",
    "cancelReasonHint": "e.g. Weather, venue issue, not enough players…",
    "dialogBack": "Back",
    "dialogCancelGameConfirm": "Cancel game",
    "messagesTitle": "Messages",
    "tooltipNewMessage": "New message",
    "failedToLoadChats": "Failed to load chats",
    "chatTitle": "Chat",
    "notParticipantInChat": "You are no longer a participant in this chat.",
    "typeMessageHint": "Type a message...",
    "messageEdited": "• edited",
    "messageDeleted": "Message deleted",
    "messageActionReply": "Reply",
    "messageActionCopyText": "Copy text",
    "messageActionPin": "Pin message",
    "messageActionUnpin": "Unpin",
    "messageActionDelete": "Delete",
    "logSessionTitle": "Log a Session",
    "sessionLoggedSuccess": "Session logged! 💪",
    "newPersonalBestTitle": "🏅 New Personal Best!",
    "awesome": "Awesome!",
    "sessionType": "Session type *",
    "outcome": "Outcome",
    "howDidYouPerform": "How did you perform? {rating}/5",
    "howDidYouFeel": "How did you feel?",
    "notes": "Notes",
    "saveSession": "Save Session 💪",
    "tooltipLogSession": "Log a session",
    "totalSessions": "Total sessions",
    "totalTime": "Total time",
    "noSessionsYet": "No sessions yet",
    "personalBests": "Personal Bests",
    "bySport": "By sport",
    "winRateTrend": "Win rate trend",
    "activity": "Activity",
    "less": "Less",
    "more": "More",
    "notificationsTitle": "Notifications",
    "markAllRead": "Mark all read",
    "snackAlreadyRatedPlayers": "You've already rated the players for this game.",
    "snackCouldNotUpdateFriendRequest": "Could not update friend request",
    "snackJoinedGame": "You joined the game.",
    "snackInviteDeclined": "Invite declined.",
    "snackActionFailed": "Action failed.",
    "snackInvitationNoLongerValid": "This invitation is no longer valid.",
    "snackPlayerApproved": "Player approved.",
    "snackJoinRequestRejected": "Join request rejected.",
    "buttonReject": "Reject",
    "emptyNotificationsTitle": "You're all caught up",
    "emptyNotificationsBody": "We'll let you know when something new happens.",
    "relativeTimeNow": "now",
    "relativeTimeMinutes": "{minutes}m",
    "relativeTimeHours": "{hours}h",
    "relativeTimeDays": "{days}d",
    "relativeTimeWeeks": "{weeks}w",
    "confirmReport": "Confirm Report",
    "continueAction": "Continue",
    "submitReportTitle": "Submit Report?",
    "goBack": "Go Back",
    "submit": "Submit",
    "reportSubmitted": "Report submitted. Admins will review it shortly.",
    "reportDetails": "Report Details",
    "reportTitleLabel": "Title",
    "reportReasonLabel": "Reason",
    "closeSearch": "Close search",
    "searchSectionGames": "Games",
    "searchSectionPlayers": "Players",
    "ratePlayerTitle": "Rate Player",
    "ratingReliability": "Reliability",
    "ratingReliabilityHint": "Did they show up on time and follow through?",
    "ratingSportsmanship": "Sportsmanship",
    "ratingSportsmanshipHint": "Were they fair, respectful, and fun to play with?",
    "ratingCommentHint": "Leave a comment (optional)...",
    "ratingSubmitAnonymously": "Submit anonymously",
    "ratingAnonymousHint": "Your name will not be shown to this player",
    "buttonSubmitRating": "Submit Rating",
    "snackRatingSubmitted": "Rating submitted!",
    "friendsTitle": "Friends",
    "dialogUnfriendTitle": "Unfriend?",
    "dialogUnfriendBody": "Remove {name} from your friends? You can send a new request later.",
    "buttonUnfriend": "Unfriend",
    "snackRemovedFromFriends": "Removed {name} from friends",
    "emptyNoFriendsYet": "No friends yet.\nVisit someone's profile and tap Add Friend.",
    "updateProfilePicture": "Update Profile Picture",
    "uploadFromGallery": "Upload from gallery",
    "choosePresetAvatar": "Choose preset avatar",
    "changePhotoOrAvatar": "Change photo or avatar",
    "personalInfo": "Personal Info",
    "dialogAddSportTitle": "Add Sport",
    "add": "Add",
    "deleteAccount": "Delete Account",
    "dialogDeleteAccountTitle": "Delete account?",
    "dialogDeleteAccountBody": "This permanently deletes your account and all data.",
    "deletePermanently": "Delete permanently",
    "adminDashboard": "Dashboard",
    "adminUsers": "Users",
    "adminReports": "Reports",
    "adminSports": "Sports",
    "adminGames": "Games",
    "failedToLoadDashboard": "Failed to load dashboard",
    "periodLast7Days": "Last 7 days",
    "periodLast30Days": "Last 30 days",
    "periodLast90Days": "Last 90 days",
    "sectionUsers": "Users",
    "statTotalUsers": "Total Users",
    "statActive30d": "Active (30d)",
    "statNewPeriod": "New (period)",
    "statBanned": "Banned",
    "statChurnRate": "Churn Rate",
    "statChurnedUsersSubtitle": "{count} users",
    "sectionRegistrations": "Registrations",
    "sectionGames": "Games",
    "statTotalGames": "Total Games",
    "statActive": "Active",
    "statCompleted": "Completed",
    "statCancelled": "Cancelled",
    "statOngoing": "Ongoing",
    "statScheduled": "Scheduled",
    "sectionPerformance": "Performance",
    "statTotalLogs": "Total Logs",
    "sectionTopSports": "Top Sports",
    "globalBroadcast": "Global Broadcast",
    "broadcastTitleLabel": "Title",
    "broadcastMessageBodyLabel": "Message body",
    "sendToAllUsers": "Send to All Users",
    "snackBroadcastSent": "Broadcast sent!",
    "snackBroadcastFailed": "Broadcast failed",
    "searchUsersHint": "Search by name, username, or email",
    "failedToLoadUsers": "Failed to load users: {error}",
    "failedToLoadGames": "Failed to load games: {error}",
    "noGamesFoundAdmin": "No games found",
    "tooltipCreateEvent": "Create event",
    "statusAll": "All",
    "statusInProgress": "In Progress",
    "statusClosed": "Closed",
    "statusUsers": "Users",
    "tooltipSortByDate": "Sort by date",
    "failedToLoadReports": "Failed to load reports: {error}",
    "noReportsFound": "No reports found",
    "adminGamesPlayedCount": "{count} games played",
    "adminStatusBanned": "Banned",
    "adminStatusRestricted": "Restricted",
    "adminActionUnban": "Unban",
    "adminActionBan": "Ban",
    "adminActionUnrestrict": "Unrestrict",
    "adminActionRestrict": "Restrict",
    "adminActionDelete": "Delete",
    "dialogDeleteUserTitle": "Delete User",
    "dialogDeleteUserBody": "This cannot be undone.",
    "extraPlayersCount": "+{count}",
    "overviewTab": "Overview",
    "logsTab": "Logs",
    "statsTab": "Stats",
    "sportRequired": "Sport *",
    "logTypeMatch": "Match",
    "logTypeTraining": "Training",
    "logTypeFitness": "Fitness",
    "outcomeWin": "Win",
    "outcomeLoss": "Loss",
    "outcomeDraw": "Draw",
    "outcomeWinBadge": "🏆 Win",
    "outcomeLossBadge": "❌ Loss",
    "outcomeDrawBadge": "🤝 Draw",
    "moodGreat": "great",
    "moodGood": "good",
    "moodOk": "ok",
    "moodTired": "tired",
    "moodInjured": "injured",
    "moodExcellent": "Excellent",
    "moodNeutral": "Neutral",
    "moodBad": "Bad",
    "moodTerrible": "Terrible",
    "durationWithMinutes": "Duration: {minutes}min",
    "sliderMinutesLabel": "{minutes} min",
    "notesHint": "What went well? What to improve?",
    "makeLogPublic": "Make this log public",
    "newPersonalBestBody": "You beat your previous record! Keep it up! 🎉",
    "newPersonalBestsCount": "{count, plural, =1{1 new personal best!} other{{count} new personal bests!}}",
    "sessionsPerWeek": "Sessions per week",
    "chartSessionCount": "{count, plural, =1{1 session} other{{count} sessions}}",
    "statsPreviewUnlock": "Your stats preview — log sessions to unlock",
    "warmingUp": "Warming up",
    "activeStreak": "Active streak",
    "daySingular": "day",
    "daysPlural": "days",
    "personalBest": "Personal best",
    "logSessionStartStreak": "Log a session today to start your streak",
    "streakGoalProgress": "{current} of {goal}-day goal · Keep it going!",
    "heatmapNoActivity": "No activity",
    "heatmapSessionCount": "{count, plural, =1{1 session} other{{count} sessions}}",
    "dayWed": "Wed",
    "dayFri": "Fri",
    "monthJan": "Jan",
    "monthFeb": "Feb",
    "monthMar": "Mar",
    "monthApr": "Apr",
    "monthMay": "May",
    "monthJun": "Jun",
    "monthJul": "Jul",
    "monthAug": "Aug",
    "monthSep": "Sep",
    "monthOct": "Oct",
    "monthNov": "Nov",
    "monthDec": "Dec",
    "snackFriendRequestAccepted": "Friend request accepted",
    "confirmReportBody": "Are you sure you want to report {targetName}? False reports may result in action against your account.",
    "reportTargetThisUser": "this user",
    "reportTargetThisGame": "this game",
    "submitReportBody": "Your report titled \"{title}\" will be sent to admins for review.",
    "reportTitleRequired": "Title is required",
    "reportReasonRequired": "Reason is required",
    "reportUser": "Report User",
    "searchMinChars": "Type at least 2 characters to search",
    "searchNoResults": "No results found",
    "searchNoResultsHint": "Try a different sport, city, or player name",
    "searchDiscoverTitle": "Discover your next game",
    "searchDiscoverSubtitle": "Search by sport, city, username, or player name",
    "searchHintNearbyGames": "Nearby games",
    "searchPartialGamesError": "Games: {error}",
    "searchPartialPlayersError": "Players: {error}",
    "adminNoUsersFound": "No users found",
    "adminNoUsersMatchSearch": "No users match \"{query}\".",
    "adminUserCount": "{count, plural, =1{1 user} other{{count} users}}",
    "failedToLoadSports": "Failed to load sports: {error}",
    "adminNoSportsYet": "No sports yet",
    "adminSportActive": "Active",
    "adminSportInactive": "Inactive",
    "adminEdit": "Edit",
    "adminDeactivateSport": "Deactivate",
    "adminEditSport": "Edit Sport",
    "fieldNameLabel": "Name",
    "fieldIconLabel": "Icon",
    "adminReporterLabel": "Reporter: @{username}",
    "adminReportedUserLabel": "Reported user: @{username}",
    "adminReportedGameLabel": "Reported game: {title}",
    "fallbackUnknown": "unknown",
    "statusLabel": "Status",
    "adminNotesLabel": "Admin notes",
    "adminSearchUserPrompt": "Type to find a user and manage their account.",
    "adminNoUsersInDatabase": "No users in the database yet.",
    "adminSearchMatchCount": "{count, plural, =1{1 match} other{{count} matches}}",
    "adminRecentUsersTotal": "Recent users ({total} total)",
    "adminViewAllResultsInUsers": "View all {total} results in Users",
    "adminOpenFullUsersList": "Open full Users list",
    "emptyNoConversations": "No conversations yet",
    "emptyConversationsHint": "Start a conversation by tapping the edit icon above or opening a game and tapping Chat.",
    "chatTypingSingle": "{names} is typing...",
    "chatTypingMultiple": "{names} are typing...",
    "replyingToName": "Replying to {name}",
    "chatMembersCount": "{count, plural, =1{1 member} other{{count} members}}",
    "pinnedMessageLabel": "Pinned message",
    "emptyNoMessagesYet": "No messages yet",
    "relativeYesterday": "Yesterday",
    "sectionNotifications": "Notifications",
    "sectionAppearance": "Appearance",
    "gameTitleHint": "e.g. Sunday 5-a-side",
    "gameTitleRequired": "Title is required",
    "gameDescriptionHint": "Optional details, rules, what to bring…",
    "addressHint": "Start typing an address...",
    "addressSelectFromSuggestions": "Select a valid address from suggestions",
    "addressVerificationFailed": "Could not verify this address. Please choose another one.",
    "pleaseSelectValidAddress": "Please select a valid address from suggestions.",
    "neighborhoodHint": "e.g. Shoreditch",
    "venueNameHint": "e.g. Hackney Marshes",
    "cityRequiredLabel": "City *",
    "cityHint": "e.g. London",
    "privateGameTitle": "Private Game (Requires Approval)",
    "privateGameSubtitleOn": "Hidden from public search. Every join request will require your approval.",
    "privateGameSubtitleOff": "Public — anyone can find and join this game.",
    "anySkillLevel": "Any level",
    "createGameButton": "Create Game 🎮",
    "sectionDetails": "Details",
    "editTitleLabel": "Title *",
    "optionalHint": "Optional",
    "sectionSchedule": "Schedule",
    "addressSelectedHint": "Selected address",
    "cityRequiredError": "City is required.",
    "venueShortLabel": "Venue",
    "calendarNoGames": "No games",
    "calendarGamesCount": "{count, plural, =1{1 game} other{{count} games}}",
    "rosterLabel": "Roster",
    "playersCountLabel": "{approved}/{max} players",
    "distanceMetersAway": "{meters} m away",
    "distanceKmAway": "{distance} km away",
    "pendingRequestsCount": "{count} pending",
    "placeCouldNotResolve": "Could not resolve this place. Try another.",
}

HE = {
    "@@locale": "he",
    "appName": "BuddBull",
    "appTagline": "מצא את הקבוצה שלך. שחק את המשחק שלך.",
    "welcomeBack": "ברוך שובך!",
    "loginSubtitle": "היכנס לחשבון BuddBull שלך",
    "emailLabel": "כתובת אימייל",
    "emailHint": "you@example.com",
    "passwordLabel": "סיסמה",
    "passwordHint": "הסיסמה שלך",
    "forgotPassword": "שכחת סיסמה?",
    "loginButton": "התחבר",
    "noAccount": "אין לך חשבון?",
    "signUpLink": "הירשם",
    "createAccount": "צור חשבון",
    "registerSubtitle": "הצטרף ל-BuddBull — בחינם!",
    "firstNameLabel": "שם פרטי",
    "firstNameHint": "אלכס",
    "lastNameLabel": "שם משפחה",
    "lastNameHint": "ריברה",
    "usernameLabel": "שם משתמש",
    "usernameHint": "@username",
    "confirmPasswordLabel": "אימות סיסמה",
    "confirmPasswordHint": "חזור על הסיסמה",
    "roleLabel": "אני רוצה…",
    "rolePlayer": "להצטרף למשחקים כשחקן",
    "roleOrganizer": "לארגן ולהוביל משחקים",
    "termsAgreement": "אני מסכים ל",
    "termsOfService": "תנאי השירות",
    "andText": " ול",
    "privacyPolicy": "מדיניות הפרטיות",
    "registerButton": "צור חשבון",
    "haveAccount": "כבר יש לך חשבון?",
    "signInLink": "התחבר",
    "resetPassword": "איפוס סיסמה",
    "forgotSubtitle": "הזן את האימייל שלך ונשלח לך קישור לאיפוס.",
    "sendResetLink": "שלח קישור איפוס",
    "backToLogin": "חזרה להתחברות",
    "resetEmailSent": "אימייל איפוס נשלח! בדוק את תיבת הדואר.",
    "myProfile": "הפרופיל שלי",
    "editProfile": "עריכת פרופיל",
    "bioLabel": "ביוגרפיה",
    "bioHint": "ספר לנו קצת על עצמך…",
    "cityLabel": "עיר",
    "neighborhoodLabel": "שכונה",
    "radiusLabel": "רדיוס חיפוש (ק\"מ)",
    "sportsInterests": "ספורט ורמות מיומנות",
    "addSport": "+ הוסף ספורט",
    "saveChanges": "שמור שינויים",
    "changePhoto": "שנה תמונה",
    "friends": "חברים",
    "gamesPlayed": "משחקים",
    "rating": "דירוג",
    "streakDays": "רצף",
    "beginner": "מתחיל",
    "amateur": "חובבן",
    "intermediate": "בינוני",
    "advanced": "מתקדם",
    "professional": "מקצועי",
    "loading": "טוען…",
    "retry": "נסה שוב",
    "cancel": "ביטול",
    "save": "שמור",
    "delete": "מחק",
    "confirm": "אישור",
    "yes": "כן",
    "no": "לא",
    "close": "סגור",
    "fieldRequired": "שדה זה נדרש.",
    "invalidEmail": "הזן כתובת אימייל תקינה.",
    "passwordTooShort": "הסיסמה חייבת להכיל לפחות 8 תווים.",
    "passwordsNoMatch": "הסיסמאות אינן תואמות.",
    "usernameTooShort": "שם המשתמש חייב להכיל לפחות 3 תווים.",
    "acceptTerms": "עליך לאשר את תנאי השירות.",
    "onboardingWelcomeMessage": "ברוך הבא ל-BuddBull! בוא נכיר אותך טוב יותר.",
    "onboardingSportsSection": "מהם הספורט האהובים עליך? הקש לבחירה — אפשר לשנות בכל עת.",
    "onboardingSkillPerSport": "הרמה שלך בכל ספורט",
    "onboardingNext": "הבא",
    "onboardingBack": "חזרה",
    "onboardingSkip": "דלג",
    "onboardingLocationTitle": "איפה אתה גר?",
    "onboardingLocationSubtitle": "אנחנו משתמשים באזור שלך כדי להתאים משחקים קרובים. בחר עיר להמשך.",
    "onboardingLocationCityHint": "התחל להקליד את העיר…",
    "onboardingLocationNeighborhoodHint": "אופציונלי — שכונה או אזור",
    "locationPermissionDenied": "נדרשת גישה למיקום כדי למצוא משחקים קרובים. אפשר להפעיל בהגדרות או לחפש לפי עיר.",
    "onboardingProfileTitle": "הפוך אותו לשלך",
    "onboardingProfileSubtitle": "העלה תמונה או בחר אווטאר Buddy. תמיד אפשר לעדכן מאוחר יותר.",
    "onboardingUploadPhoto": "העלה מהמכשיר",
    "onboardingOrPickAvatar": "או בחר אווטאר התחלתי",
    "onboardingFinish": "בוא נתחיל",
    "genericError": "משהו השתבש. נסה שוב.",
    "networkError": "אין חיבור לאינטרנט. בדוק את הרשת.",
    "serverError": "שגיאת שרת. נסה שוב מאוחר יותר.",
    "sessionExpired": "פג תוקף ההתחברות. התחבר שוב.",
    "unauthorised": "אין לך הרשאה לפעולה זו.",
    "resourceNotFound": "המשאב לא נמצא.",
    "conflictError": "אירעה התנגשות.",
    "badRequestError": "בקשה לא תקינה.",
    "validationError": "אימות נכשל.",
    "rateLimitedError": "יותר מדי בקשות. האט קצת.",
    "authFailed": "האימות נכשל. נסה שוב.",
    "navHome": "בית",
    "navGames": "משחקים",
    "navChat": "הודעות",
    "navPerformance": "ביצועים",
    "navProfile": "פרופיל",
    "oops": "אופס!",
    "language": "שפה",
    "languageEnglish": "English",
    "languageHebrew": "עברית",
    "searchGamesPlayersHint": "חפש משחקים, שחקנים…",
    "tooltipMyCalendar": "היומן שלי",
    "fabAddGame": "הוסף משחק",
    "fabLogTraining": "רשום אימון",
    "pageNotFound": "הדף לא נמצא",
    "settingsTitle": "הגדרות",
    "pushNotifications": "התראות דחיפה",
    "pushNotificationsSubtitle": "קבל התראות על פעילויות",
    "activityReminders": "תזכורות פעילות",
    "activityRemindersSubtitle": "הזכר לי לפני פעילויות מתוזמנות",
    "darkMode": "מצב כהה",
    "darkModeSubtitle": "השתמש בערכת נושא כהה",
    "appVersion": "גרסת האפליקציה",
    "notificationsEnabled": "התראות הופעלו",
    "notificationsDisabled": "התראות כובו",
    "remindersEnabled": "תזכורות פעילות הופעלו",
    "remindersDisabled": "תזכורות פעילות כובו",
    "darkModeEnabled": "מצב כהה הופעל",
    "darkModeDisabled": "מצב כהה כובה",
    "tooltipAdminDashboard": "לוח בקרה מנהל",
    "tooltipEditProfile": "עריכת פרופיל",
    "tooltipSignOut": "התנתק",
    "mutualConnections": "{count, plural, =0{אין חיבורים משותפים} =1{חיבור משותף אחד} other{{count} חיבורים משותפים}}",
    "sectionAbout": "אודות",
    "sectionLocation": "מיקום",
    "locationRadiusKm": "רדיוס {radius} ק\"מ",
    "sectionRecentActivity": "פעילות אחרונה",
    "dialogSignOutTitle": "להתנתק?",
    "dialogSignOutBody": "תצטרך להתחבר שוב.",
    "signOut": "התנתק",
    "winRatePercent": "אחוז ניצחונות",
    "communityAverageRating": "ממוצע קהילתי {rating} מ-{count} {ratingWord}",
    "ratingSingular": "דירוג",
    "ratingsPlural": "דירוגים",
    "sectionSports": "ספורט",
    "sectionRatingsSummary": "סיכום דירוגים",
    "metricOverall": "כללי",
    "metricReliability": "אמינות",
    "metricBehavior": "התנהגות",
    "sectionUpcomingGames": "משחקים קרובים",
    "snackFriendRequestSent": "בקשת חברות נשלחה",
    "snackNowFriends": "אתם חברים עכשיו",
    "snackFriendRequestDeclined": "בקשת החברות נדחתה",
    "snackSignInToMessage": "התחבר כדי לשלוח הודעה.",
    "snackCannotMessageSelf": "לא ניתן לשלוח הודעה לעצמך.",
    "buttonMessage": "הודעה",
    "buttonRequestSent": "בקשה נשלחה",
    "buttonAccept": "אשר",
    "buttonDecline": "דחה",
    "buttonAddFriend": "הוסף חבר",
    "noRatingsYet": "אין דירוגים עדיין",
    "activityDurationMinutes": "{minutes} דק'",
    "greetingGoodMorning": "בוקר טוב",
    "greetingGoodAfternoon": "צהריים טובים",
    "greetingGoodEvening": "ערב טוב",
    "greetingWithName": "{greeting}, {firstName}!",
    "greetingNoName": "{greeting}!",
    "homeCollapsedTitleFallback": "BuddBull",
    "tooltipNotifications": "התראות",
    "statGames": "משחקים",
    "statRating": "דירוג",
    "statStreak": "רצף",
    "streakDaysSuffix": "{days} ימים",
    "sectionMyUpcomingGames": "המשחקים הקרובים שלי",
    "actionSeeAll": "הצג הכל",
    "sectionExploreNearYou": "גלה בקרבתך",
    "actionBrowseAll": "עיין בהכל",
    "sectionQuickActions": "פעולות מהירות",
    "quickActionFindGame": "מצא משחק",
    "quickActionLogSession": "רשום אימון",
    "quickActionCreateGame": "צור משחק",
    "sectionRecentActivity": "פעילות אחרונה",
    "emptyNoRecentSessions": "אין אימונים אחרונים",
    "actionLogSession": "רשום אימון",
    "emptyNoUpcomingGames": "אין משחקים קרובים",
    "actionBrowseGames": "עיין במשחקים",
    "emptyCouldntLoadNearbyGames": "לא ניתן לטעון משחקים קרובים",
    "emptyNothingNearby": "אין כרגע משהו בקרבת מקום",
    "tooltipCreateGame": "צור משחק",
    "searchGamesHint": "חפש משחקים, ספורט, מיקומים…",
    "tooltipFilter": "סינון",
    "sportFilterAll": "הכל",
    "sportFootball": "כדורגל",
    "sportBasketball": "כדורסל",
    "sportTennis": "טניס",
    "sportRunning": "ריצה",
    "sportSwimming": "שחייה",
    "sportCycling": "אופניים",
    "sportVolleyball": "כדורעף",
    "sportCricket": "קריקט",
    "filtersActive": "{count, plural, =1{מסנן אחד פעיל} other{{count} מסננים פעילים}}",
    "clearFilters": "נקה",
    "emptyNoGamesFound": "לא נמצאו משחקים",
    "emptyTryAdjustingFilters": "נסה לשנות את המסננים או ליצור משחק חדש.",
    "buttonCreateGame": "צור משחק",
    "filterGames": "סינון משחקים",
    "clearAll": "נקה הכל",
    "sport": "ספורט",
    "nearMe": "קרוב אלי",
    "requiredSkillLevel": "רמת מיומנות נדרשת",
    "createGameTitle": "צור משחק",
    "gameTitleLabel": "שם המשחק *",
    "descriptionLabel": "תיאור",
    "dateAndTime": "תאריך ושעה *",
    "durationHours": "משך: {hours} ש' {minutes} דק'",
    "durationMinutesOnly": "{minutes} דק'",
    "locationRequired": "מיקום *",
    "addressLabel": "כתובת *",
    "venueNameLabel": "שם המקום",
    "maxPlayersLabel": "מקסימום שחקנים: {count}",
    "visibility": "נראות",
    "gameCreatedSuccess": "המשחק נוצר! 🎉",
    "editGameTitle": "עריכת משחק",
    "gameUpdatedSuccess": "המשחק עודכן!",
    "myCalendar": "היומן שלי",
    "today": "היום",
    "noGamesOnDay": "אין משחקים ביום זה",
    "joinRequestDeclinedSnack": "בקשת ההצטרפות נדחתה. אפשר לנסות שוב למטה.",
    "infoLabelDate": "תאריך",
    "infoLabelTime": "שעה",
    "infoLabelDuration": "משך",
    "sectionAboutThisGame": "אודות המשחק",
    "sectionOrganiser": "מארגן",
    "sectionPlayers": "שחקנים",
    "sectionMatchResult": "תוצאת המשחק",
    "sectionTags": "תגיות",
    "mapPreviewUnavailable": "תצוגת מפה לא זמינה",
    "playerListApproved": "מאושרים",
    "playerListPendingRequests": "בקשות ממתינות",
    "playerYouSuffix": "(את/ה)",
    "buttonRate": "דרג",
    "tooltipApprove": "אשר",
    "tooltipKick": "הסר",
    "ratePromptBanner": "דרג את המשתתפים למטה כדי לשתף איך עבר המשחק.",
    "matchResultScore": "תוצאה: {score}",
    "matchResultWinner": "מנצח: {winner}",
    "gameStatusOpen": "פתוח",
    "gameStatusFull": "מלא",
    "gameStatusLive": "חי",
    "gameStatusCompleted": "הושלם",
    "gameStatusCancelled": "בוטל",
    "reportGame": "דווח על משחק",
    "buttonChat": "צ'אט",
    "buttonRateParticipants": "דרג משתתפים",
    "buttonLeaveGame": "עזוב משחק",
    "buttonGameCompleted": "המשחק הושלם",
    "buttonManageOrganiser": "ניהול (מארגן)",
    "buttonGameIsFull": "המשחק מלא",
    "buttonRequestToJoin": "בקש להצטרף",
    "buttonJoinGame": "הצטרף למשחק",
    "inviteBannerTitle": "הוזמנת למשחק זה",
    "buttonAcceptInvitation": "קבל הזמנה",
    "pendingApprovalMessage": "בקשתך ממתינה לאישור",
    "buttonWithdraw": "משוך בקשה",
    "inviteFriendsSheetTitle": "הזמן חברים",
    "inviteFriendsEmptyState": "הוסף חברים מהפרופיל שלהם כדי להזמין למשחקים.",
    "buttonInvited": "הוזמן",
    "snackInvitedFriend": "הוזמן {friendName}",
    "snackRevokedInvite": "ההזמנה ל-{friendName} בוטלה",
    "manageInviteFriends": "הזמן חברים",
    "manageInviteFriendsSubtitle": "שלח הזמנה לחברים מאושרים",
    "manageEditGame": "עריכת משחק",
    "manageViewSummaryRatePlayers": "צפה בסיכום / דרג שחקנים",
    "manageViewSummarySubtitle": "המשחק הסתיים — פתח את תהליך הדירוג למשתתפים.",
    "manageCompleteGame": "סיים משחק",
    "manageCompleteGameSubtitle": "סמן את המשחק כהושלם ופתח דירוגים למשתתפים.",
    "manageGameAlreadyCancelled": "המשחק כבר בוטל",
    "manageCancelGame": "בטל משחק",
    "snackGameCancelled": "המשחק בוטל.",
    "dialogCancelGameTitle": "לבטל משחק?",
    "dialogCancelGameBody": "פעולה זו תסמן את המשחק כמבוטל לכל השחקנים.",
    "dialogYesCancel": "כן, בטל",
    "dialogCompleteGameTitle": "לסיים משחק?",
    "dialogCompleteGameBody": "פעולה זו מסמנת את המשחק כהושלם, מעדכנת סטטיסטיקות ופותחת דירוג לכל השחקנים המאושרים. לא ניתן לבטל.",
    "dialogNotYet": "לא עדיין",
    "dialogMarkCompleted": "סמן כהושלם",
    "snackCouldNotLoadPendingRatings": "לא ניתן לטעון דירוגים ממתינים. משוך לרענון ונסה שוב.",
    "fallbackPlayerName": "שחקן",
    "snackEveryoneRated": "כולם במשחק זה דורגו.",
    "rateParticipantPickerTitle": "דרג משתתף",
    "dontRateThisGame": "אל תדרג משחק זה",
    "snackWontPromptToRate": "לא תתבקש לדרג משחק זה.",
    "dialogCancelReasonTitle": "סיבת הביטול",
    "cancelReasonHint": "למשל: מזג אוויר, בעיה במקום, לא מספיק שחקנים…",
    "dialogBack": "חזרה",
    "dialogCancelGameConfirm": "בטל משחק",
    "messagesTitle": "הודעות",
    "tooltipNewMessage": "הודעה חדשה",
    "failedToLoadChats": "טעינת הצ'אטים נכשלה",
    "chatTitle": "צ'אט",
    "notParticipantInChat": "אינך עוד משתתף בצ'אט זה.",
    "typeMessageHint": "הקלד הודעה...",
    "messageEdited": "• נערך",
    "messageDeleted": "ההודעה נמחקה",
    "messageActionReply": "השב",
    "messageActionCopyText": "העתק טקסט",
    "messageActionPin": "הצמד הודעה",
    "messageActionUnpin": "בטל הצמדה",
    "messageActionDelete": "מחק",
    "logSessionTitle": "רשום אימון",
    "sessionLoggedSuccess": "האימון נרשם! 💪",
    "newPersonalBestTitle": "🏅 שיא אישי חדש!",
    "awesome": "מעולה!",
    "sessionType": "סוג אימון *",
    "outcome": "תוצאה",
    "howDidYouPerform": "איך ביצעת? {rating}/5",
    "howDidYouFeel": "איך הרגשת?",
    "notes": "הערות",
    "saveSession": "שמור אימון 💪",
    "tooltipLogSession": "רשום אימון",
    "totalSessions": "סה\"כ אימונים",
    "totalTime": "סה\"כ זמן",
    "noSessionsYet": "אין אימונים עדיין",
    "personalBests": "שיאים אישיים",
    "bySport": "לפי ספורט",
    "winRateTrend": "מגמת אחוז ניצחונות",
    "activity": "פעילות",
    "less": "פחות",
    "more": "יותר",
    "notificationsTitle": "התראות",
    "markAllRead": "סמן הכל כנקרא",
    "snackAlreadyRatedPlayers": "כבר דירגת את השחקנים במשחק זה.",
    "snackCouldNotUpdateFriendRequest": "לא ניתן לעדכן את בקשת החברות",
    "snackJoinedGame": "הצטרפת למשחק.",
    "snackInviteDeclined": "ההזמנה נדחתה.",
    "snackActionFailed": "הפעולה נכשלה.",
    "snackInvitationNoLongerValid": "ההזמנה כבר לא תקפה.",
    "snackPlayerApproved": "השחקן אושר.",
    "snackJoinRequestRejected": "בקשת ההצטרפות נדחתה.",
    "buttonReject": "דחה",
    "emptyNotificationsTitle": "הכל מעודכן",
    "emptyNotificationsBody": "נודיע לך כשיקרה משהו חדש.",
    "relativeTimeNow": "עכשיו",
    "relativeTimeMinutes": "{minutes} דק'",
    "relativeTimeHours": "{hours} ש'",
    "relativeTimeDays": "{days} ימים",
    "relativeTimeWeeks": "{weeks} שב'",
    "confirmReport": "אשר דיווח",
    "continueAction": "המשך",
    "submitReportTitle": "לשלוח דיווח?",
    "goBack": "חזרה",
    "submit": "שלח",
    "reportSubmitted": "הדיווח נשלח. מנהלים יבדקו אותו בקרוב.",
    "reportDetails": "פרטי הדיווח",
    "reportTitleLabel": "כותרת",
    "reportReasonLabel": "סיבה",
    "closeSearch": "סגור חיפוש",
    "searchSectionGames": "משחקים",
    "searchSectionPlayers": "שחקנים",
    "ratePlayerTitle": "דרג שחקן",
    "ratingReliability": "אמינות",
    "ratingReliabilityHint": "האם הגיע בזמן ועמד בהתחייבות?",
    "ratingSportsmanship": "ספורטיביות",
    "ratingSportsmanshipHint": "האם היה הוגן, מכבד וכיף לשחק איתו?",
    "ratingCommentHint": "השאר תגובה (אופציונלי)...",
    "ratingSubmitAnonymously": "שלח באנונימיות",
    "ratingAnonymousHint": "שמך לא יוצג לשחקן זה",
    "buttonSubmitRating": "שלח דירוג",
    "snackRatingSubmitted": "הדירוג נשלח!",
    "friendsTitle": "חברים",
    "dialogUnfriendTitle": "להסיר חברות?",
    "dialogUnfriendBody": "להסיר את {name} מהחברים? אפשר לשלוח בקשה חדשה מאוחר יותר.",
    "buttonUnfriend": "הסר חברות",
    "snackRemovedFromFriends": "הוסר {name} מהחברים",
    "emptyNoFriendsYet": "אין חברים עדיין.\nבקר בפרופיל של מישהו והקש הוסף חבר.",
    "updateProfilePicture": "עדכן תמונת פרופיל",
    "uploadFromGallery": "העלה מהגלריה",
    "choosePresetAvatar": "בחר אווטאר מוכן",
    "changePhotoOrAvatar": "שנה תמונה או אווטאר",
    "personalInfo": "מידע אישי",
    "dialogAddSportTitle": "הוסף ספורט",
    "add": "הוסף",
    "deleteAccount": "מחק חשבון",
    "dialogDeleteAccountTitle": "למחוק חשבון?",
    "dialogDeleteAccountBody": "פעולה זו מוחקת לצמיתות את החשבון וכל הנתונים.",
    "deletePermanently": "מחק לצמיתות",
    "adminDashboard": "לוח בקרה",
    "adminUsers": "משתמשים",
    "adminReports": "דיווחים",
    "adminSports": "ספורט",
    "adminGames": "משחקים",
    "failedToLoadDashboard": "טעינת לוח הבקרה נכשלה",
    "periodLast7Days": "7 ימים אחרונים",
    "periodLast30Days": "30 ימים אחרונים",
    "periodLast90Days": "90 ימים אחרונים",
    "sectionUsers": "משתמשים",
    "statTotalUsers": "סה\"כ משתמשים",
    "statActive30d": "פעילים (30 יום)",
    "statNewPeriod": "חדשים (תקופה)",
    "statBanned": "חסומים",
    "statChurnRate": "שיעור נטישה",
    "statChurnedUsersSubtitle": "{count} משתמשים",
    "sectionRegistrations": "הרשמות",
    "sectionGames": "משחקים",
    "statTotalGames": "סה\"כ משחקים",
    "statActive": "פעילים",
    "statCompleted": "הושלמו",
    "statCancelled": "בוטלו",
    "statOngoing": "בתהליך",
    "statScheduled": "מתוזמנים",
    "sectionPerformance": "ביצועים",
    "statTotalLogs": "סה\"כ רשומות",
    "sectionTopSports": "ספורט מוביל",
    "globalBroadcast": "שידור כללי",
    "broadcastTitleLabel": "כותרת",
    "broadcastMessageBodyLabel": "גוף ההודעה",
    "sendToAllUsers": "שלח לכל המשתמשים",
    "snackBroadcastSent": "השידור נשלח!",
    "snackBroadcastFailed": "השידור נכשל",
    "searchUsersHint": "חפש לפי שם, משתמש או אימייל",
    "failedToLoadUsers": "טעינת משתמשים נכשלה: {error}",
    "failedToLoadGames": "טעינת משחקים נכשלה: {error}",
    "noGamesFoundAdmin": "לא נמצאו משחקים",
    "tooltipCreateEvent": "צור אירוע",
    "statusAll": "הכל",
    "statusInProgress": "בטיפול",
    "statusClosed": "סגור",
    "statusUsers": "משתמשים",
    "tooltipSortByDate": "מיין לפי תאריך",
    "failedToLoadReports": "טעינת דיווחים נכשלה: {error}",
    "noReportsFound": "לא נמצאו דיווחים",
    "adminGamesPlayedCount": "{count} משחקים שוחקו",
    "adminStatusBanned": "חסום",
    "adminStatusRestricted": "מוגבל",
    "adminActionUnban": "בטל חסימה",
    "adminActionBan": "חסום",
    "adminActionUnrestrict": "בטל הגבלה",
    "adminActionRestrict": "הגבל",
    "adminActionDelete": "מחק",
    "dialogDeleteUserTitle": "מחק משתמש",
    "dialogDeleteUserBody": "לא ניתן לבטל פעולה זו.",
    "extraPlayersCount": "+{count}",
    "overviewTab": "סקירה",
    "logsTab": "יומן",
    "statsTab": "סטטיסטיקה",
    "sportRequired": "ספורט *",
    "logTypeMatch": "משחק",
    "logTypeTraining": "אימון",
    "logTypeFitness": "כושר",
    "outcomeWin": "ניצחון",
    "outcomeLoss": "הפסד",
    "outcomeDraw": "תיקו",
    "outcomeWinBadge": "🏆 ניצחון",
    "outcomeLossBadge": "❌ הפסד",
    "outcomeDrawBadge": "🤝 תיקו",
    "moodGreat": "מעולה",
    "moodGood": "טוב",
    "moodOk": "בסדר",
    "moodTired": "עייף",
    "moodInjured": "פצוע",
    "moodExcellent": "מצוין",
    "moodNeutral": "ניטרלי",
    "moodBad": "רע",
    "moodTerrible": "נורא",
    "durationWithMinutes": "משך: {minutes} דק'",
    "sliderMinutesLabel": "{minutes} דק'",
    "notesHint": "מה הלך טוב? מה לשפר?",
    "makeLogPublic": "הפוך רשומה זו לציבורית",
    "newPersonalBestBody": "שברת את השיא הקודם שלך! המשך כך! 🎉",
    "newPersonalBestsCount": "{count, plural, =1{שיא אישי חדש אחד!} other{{count} שיאים אישיים חדשים!}}",
    "sessionsPerWeek": "אימונים בשבוע",
    "chartSessionCount": "{count, plural, =1{אימון אחד} other{{count} אימונים}}",
    "statsPreviewUnlock": "תצוגה מקדימה של הסטטיסטיקה — רשום אימונים כדי לפתוח",
    "warmingUp": "מתחמם",
    "activeStreak": "רצף פעיל",
    "daySingular": "יום",
    "daysPlural": "ימים",
    "personalBest": "שיא אישי",
    "logSessionStartStreak": "רשום אימון היום כדי להתחיל רצף",
    "streakGoalProgress": "{current} מתוך יעד של {goal} ימים · המשך כך!",
    "heatmapNoActivity": "אין פעילות",
    "heatmapSessionCount": "{count, plural, =1{אימון אחד} other{{count} אימונים}}",
    "dayWed": "ד'",
    "dayFri": "ו'",
    "monthJan": "ינו'",
    "monthFeb": "פבר'",
    "monthMar": "מרץ",
    "monthApr": "אפר'",
    "monthMay": "מאי",
    "monthJun": "יוני",
    "monthJul": "יולי",
    "monthAug": "אוג'",
    "monthSep": "ספט'",
    "monthOct": "אוק'",
    "monthNov": "נוב'",
    "monthDec": "דצמ'",
    "snackFriendRequestAccepted": "בקשת החברות אושרה",
    "confirmReportBody": "האם אתה בטוח שברצונך לדווח על {targetName}? דיווחים כוזבים עלולים לגרום לפעולה נגד חשבונך.",
    "reportTargetThisUser": "משתמש זה",
    "reportTargetThisGame": "משחק זה",
    "submitReportBody": "הדיווח שלך בשם \"{title}\" יישלח למנהלים לבדיקה.",
    "reportTitleRequired": "כותרת נדרשת",
    "reportReasonRequired": "סיבה נדרשת",
    "reportUser": "דווח על משתמש",
    "searchMinChars": "הקלד לפחות 2 תווים לחיפוש",
    "searchNoResults": "לא נמצאו תוצאות",
    "searchNoResultsHint": "נסה ספורט, עיר או שם שחקן אחר",
    "searchDiscoverTitle": "גלה את המשחק הבא שלך",
    "searchDiscoverSubtitle": "חפש לפי ספורט, עיר, שם משתמש או שם שחקן",
    "searchHintNearbyGames": "משחקים קרובים",
    "searchPartialGamesError": "משחקים: {error}",
    "searchPartialPlayersError": "שחקנים: {error}",
    "gameTitleHint": "למשל: כדורגל 5 נגד 5 ביום ראשון",
    "gameTitleRequired": "שם המשחק נדרש",
    "gameDescriptionHint": "פרטים אופציונליים, כללים, מה להביא…",
    "addressHint": "התחל להקליד כתובת...",
    "addressSelectFromSuggestions": "בחר כתובת תקינה מההצעות",
    "addressVerificationFailed": "לא ניתן לאמת כתובת זו. בחר כתובת אחרת.",
    "pleaseSelectValidAddress": "בחר כתובת תקינה מההצעות.",
    "neighborhoodHint": "למשל: שכונת XYZ",
    "venueNameHint": "למשל: מגרש ספורט מרכזי",
    "cityRequiredLabel": "עיר *",
    "cityHint": "למשל: תל אביב",
    "privateGameTitle": "משחק פרטי (דורש אישור)",
    "privateGameSubtitleOn": "מוסתר מחיפוש ציבורי. כל בקשת הצטרפות תדרוש את אישורך.",
    "privateGameSubtitleOff": "ציבורי — כולם יכולים למצוא ולהצטרף למשחק.",
    "anySkillLevel": "כל רמה",
    "createGameButton": "צור משחק 🎮",
    "sectionDetails": "פרטים",
    "editTitleLabel": "שם *",
    "optionalHint": "אופציונלי",
    "sectionSchedule": "לוח זמנים",
    "addressSelectedHint": "כתובת שנבחרה",
    "cityRequiredError": "עיר נדרשת.",
    "venueShortLabel": "מקום",
    "calendarNoGames": "אין משחקים",
    "calendarGamesCount": "{count, plural, =1{משחק אחד} other{{count} משחקים}}",
    "rosterLabel": "סגל",
    "playersCountLabel": "{approved}/{max} שחקנים",
    "distanceMetersAway": "{meters} מ' מכאן",
    "distanceKmAway": "{distance} ק\"מ מכאן",
    "pendingRequestsCount": "{count} ממתינים",
    "placeCouldNotResolve": "לא ניתן לאתר מקום זה. נסה אחר.",
    "adminNoUsersMatchSearch": "אין משתמשים התואמים ל-\"{query}\".",
    "adminUserCount": "{count, plural, =1{משתמש אחד} other{{count} משתמשים}}",
    "failedToLoadSports": "טעינת ספורט נכשלה: {error}",
    "adminReporterLabel": "מדווח: @{username}",
    "adminReportedUserLabel": "משתמש מדווח: @{username}",
    "adminReportedGameLabel": "משחק מדווח: {title}",
    "adminSearchMatchCount": "{count, plural, =1{התאמה אחת} other{{count} התאמות}}",
    "adminRecentUsersTotal": "משתמשים אחרונים ({total} סה\"כ)",
    "adminViewAllResultsInUsers": "הצג את כל {total} התוצאות במשתמשים",
    "chatTypingSingle": "{names} מקליד...",
    "chatTypingMultiple": "{names} מקלידים...",
    "replyingToName": "משיב ל-{name}",
    "chatMembersCount": "{count, plural, =1{חבר אחד} other{{count} חברים}}",
    "sectionAppearance": "מראה",
    "sectionNotifications": "התראות",
    "relativeYesterday": "אתמול",
    "emptyNoMessagesYet": "אין הודעות עדיין",
    "pinnedMessageLabel": "הודעה מוצמדת",
    "emptyConversationsHint": "התחל שיחה על ידי לחיצה על סמל העריכה למעלה או פתיחת משחק ולחיצה על צ'אט.",
    "emptyNoConversations": "אין שיחות עדיין",
    "adminOpenFullUsersList": "פתח רשימת משתמשים מלאה",
    "adminNoUsersInDatabase": "אין משתמשים במסד הנתונים עדיין.",
    "adminSearchUserPrompt": "הקלד כדי למצוא משתמש ולנהל את החשבון שלו.",
    "adminNotesLabel": "הערות מנהל",
    "statusLabel": "סטטוס",
    "fallbackUnknown": "לא ידוע",
    "fieldIconLabel": "אייקון",
    "fieldNameLabel": "שם",
    "adminEditSport": "עריכת ספורט",
    "adminDeactivateSport": "השבת",
    "adminEdit": "ערוך",
    "adminSportInactive": "לא פעיל",
    "adminSportActive": "פעיל",
    "adminNoSportsYet": "אין ספורט עדיין",
    "adminNoUsersFound": "לא נמצאו משתמשים",

}

META = {
    "mutualConnections": {"placeholders": {"count": {"type": "int"}}},
    "locationRadiusKm": {"placeholders": {"radius": {"type": "int"}}},
    "communityAverageRating": {
        "placeholders": {
            "rating": {"type": "String"},
            "count": {"type": "int"},
            "ratingWord": {"type": "String"},
        }
    },
    "activityDurationMinutes": {"placeholders": {"minutes": {"type": "int"}}},
    "greetingWithName": {
        "placeholders": {
            "greeting": {"type": "String"},
            "firstName": {"type": "String"},
        }
    },
    "greetingNoName": {"placeholders": {"greeting": {"type": "String"}}},
    "streakDaysSuffix": {"placeholders": {"days": {"type": "int"}}},
    "filtersActive": {"placeholders": {"count": {"type": "int"}}},
    "durationHours": {
        "placeholders": {"hours": {"type": "int"}, "minutes": {"type": "int"}}
    },
    "durationMinutesOnly": {"placeholders": {"minutes": {"type": "int"}}},
    "maxPlayersLabel": {"placeholders": {"count": {"type": "int"}}},
    "matchResultScore": {"placeholders": {"score": {"type": "String"}}},
    "matchResultWinner": {"placeholders": {"winner": {"type": "String"}}},
    "snackInvitedFriend": {"placeholders": {"friendName": {"type": "String"}}},
    "snackRevokedInvite": {"placeholders": {"friendName": {"type": "String"}}},
    "relativeTimeMinutes": {"placeholders": {"minutes": {"type": "int"}}},
    "relativeTimeHours": {"placeholders": {"hours": {"type": "int"}}},
    "relativeTimeDays": {"placeholders": {"days": {"type": "int"}}},
    "relativeTimeWeeks": {"placeholders": {"weeks": {"type": "int"}}},
    "dialogUnfriendBody": {"placeholders": {"name": {"type": "String"}}},
    "snackRemovedFromFriends": {"placeholders": {"name": {"type": "String"}}},
    "statChurnedUsersSubtitle": {"placeholders": {"count": {"type": "int"}}},
    "failedToLoadUsers": {"placeholders": {"error": {"type": "String"}}},
    "failedToLoadGames": {"placeholders": {"error": {"type": "String"}}},
    "failedToLoadReports": {"placeholders": {"error": {"type": "String"}}},
    "adminGamesPlayedCount": {"placeholders": {"count": {"type": "int"}}},
    "extraPlayersCount": {"placeholders": {"count": {"type": "int"}}},
    "howDidYouPerform": {"placeholders": {"rating": {"type": "int"}}},
    "durationWithMinutes": {"placeholders": {"minutes": {"type": "int"}}},
    "sliderMinutesLabel": {"placeholders": {"minutes": {"type": "int"}}},
    "newPersonalBestsCount": {"placeholders": {"count": {"type": "int"}}},
    "chartSessionCount": {"placeholders": {"count": {"type": "int"}}},
    "streakGoalProgress": {
        "placeholders": {"current": {"type": "int"}, "goal": {"type": "int"}}
    },
    "heatmapSessionCount": {"placeholders": {"count": {"type": "int"}}},
    "confirmReportBody": {"placeholders": {"targetName": {"type": "String"}}},
    "submitReportBody": {"placeholders": {"title": {"type": "String"}}},
    "searchPartialGamesError": {"placeholders": {"error": {"type": "String"}}},
    "searchPartialPlayersError": {"placeholders": {"error": {"type": "String"}}},
    "calendarGamesCount": {"placeholders": {"count": {"type": "int"}}},
    "playersCountLabel": {
        "placeholders": {"approved": {"type": "int"}, "max": {"type": "int"}}
    },
    "distanceMetersAway": {"placeholders": {"meters": {"type": "int"}}},
    "distanceKmAway": {"placeholders": {"distance": {"type": "String"}}},
    "pendingRequestsCount": {"placeholders": {"count": {"type": "int"}}},
    "adminNoUsersMatchSearch": {"placeholders": {"query": {"type": "String"}}},
    "adminUserCount": {"placeholders": {"count": {"type": "int"}}},
    "failedToLoadSports": {"placeholders": {"error": {"type": "String"}}},
    "adminReporterLabel": {"placeholders": {"username": {"type": "String"}}},
    "adminReportedUserLabel": {"placeholders": {"username": {"type": "String"}}},
    "adminReportedGameLabel": {"placeholders": {"title": {"type": "String"}}},
    "adminSearchMatchCount": {"placeholders": {"count": {"type": "int"}}},
    "adminRecentUsersTotal": {"placeholders": {"total": {"type": "int"}}},
    "adminViewAllResultsInUsers": {"placeholders": {"total": {"type": "int"}}},
    "chatTypingSingle": {"placeholders": {"names": {"type": "String"}}},
    "chatTypingMultiple": {"placeholders": {"names": {"type": "String"}}},
    "replyingToName": {"placeholders": {"name": {"type": "String"}}},
    "chatMembersCount": {"placeholders": {"count": {"type": "int"}}},
}


def build_arb(locale_data: dict) -> dict:
    out = {}
    for key, value in locale_data.items():
        out[key] = value
        if key.startswith("@@"):
            continue
        if key in META:
            out["@" + key] = META[key]
    return out


def main() -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    with open(ROOT / "app_en.arb", "w", encoding="utf-8") as f:
        json.dump(build_arb(EN), f, ensure_ascii=False, indent=2)
    with open(ROOT / "app_he.arb", "w", encoding="utf-8") as f:
        json.dump(build_arb(HE), f, ensure_ascii=False, indent=2)
    print(f"Generated {len(EN) - 1} keys")


if __name__ == "__main__":
    main()
