// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD70Ce7nFRsWnYmg7kHUzWg77V3Kw7rYBc',
    appId: '1:577177214284:web:7c44be884c901f80c4c3e9',
    messagingSenderId: '577177214284',
    projectId: 'budbull-app',
    authDomain: 'budbull-app.firebaseapp.com',
    storageBucket: 'budbull-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7IronnJICfvWrMS12OqsyB1Zhp7gIL5E',
    appId: '1:577177214284:android:5e80b080db0c297ac4c3e9',
    messagingSenderId: '577177214284',
    projectId: 'budbull-app',
    storageBucket: 'budbull-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUboP4vtcXIWwSN21TVhSpdGSAFjsxW6c',
    appId: '1:577177214284:ios:eea16209495876bdc4c3e9',
    messagingSenderId: '577177214284',
    projectId: 'budbull-app',
    storageBucket: 'budbull-app.firebasestorage.app',
    iosBundleId: 'com.example.buddbull',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUboP4vtcXIWwSN21TVhSpdGSAFjsxW6c',
    appId: '1:577177214284:ios:eea16209495876bdc4c3e9',
    messagingSenderId: '577177214284',
    projectId: 'budbull-app',
    storageBucket: 'budbull-app.firebasestorage.app',
    iosBundleId: 'com.example.buddbull',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD70Ce7nFRsWnYmg7kHUzWg77V3Kw7rYBc',
    appId: '1:577177214284:web:e35958e3e5e0a0ebc4c3e9',
    messagingSenderId: '577177214284',
    projectId: 'budbull-app',
    authDomain: 'budbull-app.firebaseapp.com',
    storageBucket: 'budbull-app.firebasestorage.app',
  );
}
