// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGaWAK0p3g6-z24DkrHWOmjZsaNs5Bz6E',
    appId: '1:242098642508:web:c58b8f456d3950ae361ee9',
    messagingSenderId: '242098642508',
    projectId: 'newbudd-3f822',
    authDomain: 'newbudd-3f822.firebaseapp.com',
    storageBucket: 'newbudd-3f822.firebasestorage.app',
    measurementId: 'G-5MHMM6ZSEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcI6eXrAJndJaXRNhhmFlGPfVJ0jJPBms',
    appId: '1:242098642508:android:bbbd6998ae512ff7361ee9',
    messagingSenderId: '242098642508',
    projectId: 'newbudd-3f822',
    storageBucket: 'newbudd-3f822.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGMPX--ozkwoB7IzW7_Ekj5JRXvNLJsbI',
    appId: '1:242098642508:ios:69464002c211574a361ee9',
    messagingSenderId: '242098642508',
    projectId: 'newbudd-3f822',
    storageBucket: 'newbudd-3f822.firebasestorage.app',
    iosBundleId: 'com.buddbull.buddbull',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGMPX--ozkwoB7IzW7_Ekj5JRXvNLJsbI',
    appId: '1:242098642508:ios:69464002c211574a361ee9',
    messagingSenderId: '242098642508',
    projectId: 'newbudd-3f822',
    storageBucket: 'newbudd-3f822.firebasestorage.app',
    iosBundleId: 'com.buddbull.buddbull',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGaWAK0p3g6-z24DkrHWOmjZsaNs5Bz6E',
    appId: '1:242098642508:web:089e7c3049e6d5b6361ee9',
    messagingSenderId: '242098642508',
    projectId: 'newbudd-3f822',
    authDomain: 'newbudd-3f822.firebaseapp.com',
    storageBucket: 'newbudd-3f822.firebasestorage.app',
    measurementId: 'G-5QM9LR7TS8',
  );
}
