import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Core Firebase package
import 'firebase_options.dart'; // The file generated by FlutterFire CLI
import 'screens/splash_screen.dart';
import 'screens/form_fill_screen.dart';
import 'screens/login_screen.dart';

void main() async {
  // 1. Ensure Flutter framework is fully loaded before starting
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase connection using the generated options
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // 3. Start the application
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false, // Removes the "Debug" banner
      title: 'BudBull',
      theme: ThemeData(useMaterial3: true, primarySwatch: Colors.blue),
      // Setting the RegisterScreen as the first thing the user sees
      home: const SplashScreen(),
      onGenerateRoute: (settings) {
        switch (settings.name) {
          case 'form_fill_screen':
            final args = settings.arguments as Map<String, dynamic>?;
            return MaterialPageRoute(
              builder: (context) => FormFillScreen(
                initialEmail: args?['initialEmail'] as String?,
              ),
            );
          case 'login_screen':
            return MaterialPageRoute(builder: (context) => const LoginScreen());

          default:
            return null;
        }
      },
      onUnknownRoute: (settings) {
        return MaterialPageRoute(
          builder: (context) => Scaffold(
            appBar: AppBar(title: const Text('Page Not Found')),
            body: Center(child: Text('Route "${settings.name}" not found')),
          ),
        );
      },
    );
  }
}
